# Generated by Django 5.2 on 2026-04-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancewarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attendance/leaves/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('casual', 'Casual'), ('duty', 'Duty'), ('sports', 'Sports')], default='casual', max_length=20),
        ),
    ]
