# Generated by Django 5.2 on 2026-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverequest_attachment_leaverequest_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='leave_certificates/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('medical', 'Medical'), ('duty', 'Duty'), ('sports', 'Sports')], default='casual', max_length=20),
        ),
    ]
