# Generated by Django 5.2 on 2026-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_leaverequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('casual', 'Casual'), ('duty', 'Duty'), ('sports', 'Sports')], default='casual', max_length=20),
        ),
    ]
