# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("students", "0002_rename_date_of_admission_student_admission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="students.section",
            ),
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"db_table": "notifications", "ordering": ["-is_pinned", "-created_at"]},
        ),
    ]

