# Generated by Django 6.0.2 on 2026-04-01 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_rename_date_of_admission_student_admission_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostelBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_rooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "warden",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_blocks",
            },
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=20)),
                ("capacity", models.PositiveSmallIntegerField(default=4)),
                ("occupied", models.PositiveSmallIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.hostelblock",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_rooms",
                "unique_together": {("block", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="HostelAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField()),
                ("leave_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allotment",
                        to="students.student",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_allotments",
            },
        ),
    ]
