# Generated by Django 6.0.3 on 2026-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
