# Generated by Django 5.2 on 2026-04-09 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_messconsumptionlog_messdietprofile_messfeedback_and_more'),
        ('students', '0004_student_previous_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenuplan',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messconsumptionlog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messmealattendance',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messmenuplan',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messwastagelog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20),
        ),
        migrations.CreateModel(
            name='MessFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('juice', 'Juice')], max_length=20)),
                ('items', models.TextField()),
                ('is_veg', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_orders', to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_orders', to='students.student')),
            ],
            options={
                'db_table': 'mess_food_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
