# Generated by Django 5.2 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0005_messmenuplan_is_veg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messvendor",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

