# Generated by Django 5.2 on 2026-04-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_messvendor_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messmenuplan',
            name='is_veg',
        ),
        migrations.AddField(
            model_name='messvendorsupply',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
