# Generated by Django 5.2 on 2026-04-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_remove_messmenuplan_is_veg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messconsumptionlog',
            name='student_count',
        ),
    ]
