# Generated by Django 5.2 on 2026-04-11 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_remove_messconsumptionlog_student_count'),
        ('students', '0004_student_previous_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='category',
            field=models.CharField(choices=[('junior', 'Junior (1-7)'), ('senior', 'Senior (8-12)')], default='junior', max_length=10),
        ),
        migrations.AlterField(
            model_name='messconsumptionlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='messfoodorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='messmealattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='messvendorsupply',
            name='supply_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='messwastagelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='nightattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='ruleviolation',
            name='violation_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='StudentHostelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_hostel_type', models.CharField(choices=[('boys', 'Boys Only'), ('girls', 'Girls Only'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('friend_ids', models.JSONField(blank=True, default=list, help_text='List of student IDs/admission numbers of preferred roommates')),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_preference', to='students.student')),
            ],
            options={
                'db_table': 'hostel_preferences',
            },
        ),
    ]
