# Generated by Django 6.0.3 on 2026-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_coordinator_exam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('Descriptive', 'Descriptive'), ('True/False', 'True/False')], default='MCQ', max_length=50),
        ),
    ]
