# Generated by Django 6.0.3 on 2026-04-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_questionbank_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='max_internal_marks',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='examtype',
            name='max_theory_marks',
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
