# Generated by Django 6.0.3 on 2026-04-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_remove_subjectallocation_teachers_and_more'),
        ('exams', '0005_examtype_max_internal_marks_and_more'),
        ('staff', '0003_teacherdetail_teaching_subjects'),
        ('students', '0006_alter_section_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grading_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('result_visibility', models.CharField(choices=[('instant', 'Publish Immediately'), ('review', 'Teacher Reviews First')], default='review', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Countdown timer in minutes. Null = no limit.', null=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='When the test becomes available.', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='When the test closes.', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_tests_created', to='staff.staff')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tests', to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tests', to='academics.subject')),
            ],
            options={
                'db_table': 'online_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('published', 'Published')], default='in_progress', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts_v2', to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.onlinetest')),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
                'unique_together': {('test', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ — Single Choice'), ('mcq_multi', 'MCQ — Multiple Choice'), ('short', 'Short Answer'), ('long', 'Long / Descriptive'), ('truefalse', 'True / False'), ('fill', 'Fill in the Blank'), ('upload', 'File Upload'), ('divider', 'Section Divider')], default='mcq_single', max_length=20)),
                ('text', models.TextField(help_text='The question prompt. Supports markdown.')),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_required', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_questions/')),
                ('accepted_answers', models.JSONField(blank=True, default=list, help_text='For fill-in-the-blank: ["answer1", "synonym"]. Case-insensitive matching.')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='exams.onlinetest')),
            ],
            options={
                'db_table': 'test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.testquestion')),
            ],
            options={
                'db_table': 'test_choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='test_uploads/')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('teacher_remark', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.testattempt')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='exams.testchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='exams.testquestion')),
            ],
            options={
                'db_table': 'test_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
