# Generated by Django 6.0.2 on 2026-04-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="medical_notes",
            new_name="allergies",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="father_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="father_occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="health_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mother_occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
