# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_parent_guardian_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/signatures/"),
        ),
    ]
