# Generated by Django 6.0.2 on 2026-04-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_signature"),
        ("permissions", "0001_initial"),
        ("students", "0004_student_previous_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_teachers",
                to="students.class",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="portal",
            field=models.CharField(
                choices=[
                    ("admin", "Admin Portal"),
                    ("student", "Student Portal"),
                    ("parent", "Parent Portal"),
                    ("creator", "Creator Portal"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="permissions.role",
            ),
        ),
    ]
