# Generated by Django 6.0.2 on 2026-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_assigned_class_user_portal_alter_role_name_and_more"),
        (
            "permissions",
            "0002_alter_permission_options_permission_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="individual_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Extra permissions granted to this user on top of their role",
                related_name="users_individual",
                to="permissions.permission",
            ),
        ),
    ]
