# Generated by Django 6.0.3 on 2026-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#00a676', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
