# Generated by Django 6.0.3 on 2026-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_school_primary_color_school_secondary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portal',
            field=models.CharField(choices=[('admin', 'Admin Portal'), ('student', 'Student Portal'), ('parent', 'Parent Portal')], default='admin', max_length=20),
        ),
    ]
