# Generated by Django 6.0.3 on 2026-04-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_class',
        ),
    ]
