# Generated by Django 6.0.3 on 2026-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='working_days',
            field=models.JSONField(default=list, help_text='List of working day indices (1=Mon, 7=Sun)'),
        ),
    ]
