# Generated by Django 6.0.3 on 2026-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='timetable_config',
            field=models.JSONField(blank=True, default=dict, help_text='Stores periods, breaks, and time settings'),
        ),
    ]
