# Generated by Django 6.0.2 on 2026-04-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"ordering": ["module", "codename"]},
        ),
        migrations.AddField(
            model_name="permission",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Plain-English explanation shown to non-technical users",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="module",
            field=models.CharField(
                default="other",
                help_text="Grouping category e.g. Students, Fees, Attendance",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[
                    ("school", "School-wide"),
                    ("class", "Own Class Only"),
                    ("subject", "Own Subjects Only"),
                    ("self", "Self Only"),
                ],
                default="school",
                help_text="Default data scope for this role",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PermissionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("role", "Role"), ("user", "User")], max_length=10
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("granted", "Granted"), ("revoked", "Revoked")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="permissions.permission",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="permissions.role",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "permission_change_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
