# Generated by Django 6.0.3 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_options_permission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True if dynamically assigned by system, do not show in manual dropdowns'),
        ),
    ]
