# Generated by Django 6.0.2 on 2026-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="homework/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "homework",
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="homework/submissions/"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("grade", models.CharField(blank=True, max_length=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_late", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "homework_submissions",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_number", models.PositiveSmallIntegerField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("break", "Break"),
                            ("lunch", "Lunch"),
                            ("free", "Free"),
                        ],
                        default="class",
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "periods",
                "ordering": ["period_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("max_marks", models.PositiveSmallIntegerField(default=100)),
                ("is_optional", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="SubstituteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "substitute_logs",
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "timetables",
            },
        ),
    ]
