# Generated by Django 6.0.2 on 2026-03-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_homework",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_list",
                to="students.section",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="academics.homework",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_submissions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="students.class",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_list",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="substitutelog",
            name="original_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substituted_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="substitutelog",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_logs",
                to="academics.period",
            ),
        ),
        migrations.AddField(
            model_name="substitutelog",
            name="substitute_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="accounts.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="students.section",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="academics.timetable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="homeworksubmission",
            unique_together={("homework", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school_class", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("section", "academic_year", "day_of_week")},
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("timetable", "period_number")},
        ),
    ]
