# Generated by Django 6.0.2 on 2026-04-03 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_subject_unique_together_subject_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectallocation",
            name="teacher",
        ),
        migrations.AddField(
            model_name="subjectallocation",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="allocated_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SyllabusTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="academics.syllabuschapter",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_topics",
                "ordering": ["order"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="lessonplan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to="academics.syllabustopic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonplan",
            unique_together={("allocation", "topic")},
        ),
        migrations.RemoveField(
            model_name="lessonplan",
            name="chapter",
        ),
    ]
