# Generated by Django 6.0.2 on 2026-04-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_remove_subjectallocation_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonplan",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to="academics.subjectallocation",
            ),
        ),
    ]
