# Generated by Django 6.0.3 on 2026-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_school_subject_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color_code',
            field=models.CharField(default='#3b82f6', help_text='Hex color for timetable display.', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_periods',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of periods per week for this subject.'),
        ),
    ]
