# Generated by Django 6.0.3 on 2026-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_color_code_subject_weekly_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Custom name for event periods (e.g. CCA, Assembly)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('class', 'Class'), ('break', 'Break'), ('lunch', 'Lunch'), ('free', 'Free'), ('event', 'Event')], default='class', max_length=10),
        ),
    ]
