# Generated by Django 5.2.13 on 2026-04-13 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_period_custom_title_alter_period_period_type'),
        ('accounts', '0011_remove_user_assigned_class'),
        ('students', '0004_student_previous_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('class', 'Class'), ('break', 'Break'), ('lunch', 'Lunch'), ('free', 'Free'), ('custom', 'Custom')], default='class', max_length=10),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab / Practical'), ('tutorial', 'Tutorial'), ('revision', 'Revision'), ('test', 'Class Test'), ('other', 'Other')], default='lecture', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional label; defaults to subject name if blank.', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='accounts.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_sessions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_sessions',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
