# Generated by Django 6.0.3 on 2026-04-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_course_session'),
        ('accounts', '0011_remove_user_assigned_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('global_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'global_subjects',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='term_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('semester', 'Semester'), ('quarter', 'Quarter')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color_code',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabusunit',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='global_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_instances', to='academics.globalsubject'),
        ),
        migrations.CreateModel(
            name='SubjectBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_bundles', to='accounts.school')),
                ('subjects', models.ManyToManyField(related_name='bundles', to='academics.globalsubject')),
            ],
            options={
                'db_table': 'subject_bundles',
            },
        ),
        migrations.CreateModel(
            name='SyllabusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.globalsubject')),
            ],
            options={
                'db_table': 'syllabus_masters',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_instances', to='academics.syllabusmaster'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.syllabusmaster'),
        ),
    ]
