# Generated by Django 6.0.3 on 2026-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_globalsubject_subject_term_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
