# Generated by Django 5.2.13 on 2026-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_timetable_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='submitted', max_length=20),
        ),
    ]
