# Generated by Django 6.0.3 on 2026-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_timetable_day_of_week'),
        ('students', '0006_alter_section_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school_class', 'code'), ('school_class', 'name')},
        ),
    ]
