# Generated by Django 6.0.3 on 2026-04-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_subject_code_alter_subject_unique_together'),
        ('academics', '0013_homeworksubmission_status'),
    ]

    operations = [
    ]
