# Generated by Django 5.2.13 on 2026-04-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_subject_code_alter_subject_unique_together'),
        ('academics', '0013_homeworksubmission_status'),
    ]

    operations = [
    ]
