# Generated by Django 6.0.3 on 2026-04-18 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_merge_20260418_1233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectallocation',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, help_text='Temporary substitute teacher assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
