# Generated by Django 6.0.3 on 2026-04-25

from __future__ import annotations

from django.db import migrations, models


def ensure_pe_subjects(apps, schema_editor):
    Subject = apps.get_model("academics", "Subject")
    SchoolClass = apps.get_model("students", "Class")

    for school_class in SchoolClass.objects.all():
        subject, created = Subject.objects.get_or_create(
            school_class_id=school_class.id,
            code="PT",
            defaults={
                "school_id": getattr(school_class, "school_id", None),
                "name": "Physical Education",
                "description": "Physical Training / Physical Education",
                "weekly_periods": 2,
                "color_code": "#22c55e",
                "term_type": "annual",
                "is_active": True,
                "is_compulsory": True,
            },
        )
        if not created and not getattr(subject, "is_compulsory", False):
            subject.is_compulsory = True
            subject.save(update_fields=["is_compulsory"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0015_remove_subjectallocation_teachers_and_more"),
        ("students", "0006_alter_section_class_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_compulsory",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(ensure_pe_subjects, migrations.RunPython.noop),
    ]
