# Generated by Django 6.0.3 on 2026-04-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0014_merge_20260418_1043"),
        ("academics", "0015_remove_subjectallocation_teachers_and_more"),
    ]

    operations = []
