# Generated by Django 6.0.2 on 2026-03-31 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="date_of_admission",
            new_name="admission_date",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="current_section",
            new_name="section",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_class",
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_resident",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_user",
            field=models.BooleanField(default=False),
        ),
    ]
