# Generated by Django 6.0.2 on 2026-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="previous_school",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
