# Generated by Django 5.2.13 on 2026-04-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_assigned_class'),
        ('students', '0004_student_previous_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Enrolled', 'Enrolled')], default='New', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('class_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_inquiries', to='students.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_inquiries', to='accounts.school')),
            ],
            options={
                'db_table': 'admission_inquiries',
                'ordering': ['-inquiry_date'],
            },
        ),
    ]
