# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_rename_date_of_admission_student_admission_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("role", models.CharField(default="Class Leader", max_length=120)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ongoing", "Ongoing"), ("ended", "Ended")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="elections_created", to=settings.AUTH_USER_MODEL)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="elections", to="students.section")),
            ],
            options={"db_table": "elections", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("image_data", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("election", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="elections.election")),
            ],
            options={"db_table": "election_candidates", "ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("roll_number", models.CharField(max_length=32)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="elections.candidate")),
                ("election", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="elections.election")),
            ],
            options={"db_table": "election_votes"},
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=("election", "roll_number"), name="uniq_vote_per_roll_per_election"),
        ),
    ]

