# Generated by Django 6.0.3 on 2026-04-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('students', '0004_student_previous_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='students.section'),
        ),
    ]
