# Generated by Django 5.2 on 2026-04-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
        ('students', '0004_student_previous_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('items', models.ManyToManyField(to='canteen.fooditem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_orders', to='students.student')),
            ],
            options={
                'db_table': 'canteen_orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
