# Generated by Django 5.2 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_canteenorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='items',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
