# Generated by Django 5.2 on 2026-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_remove_dailymenu_items_dailymenu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='special_note',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='dish_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
