# Generated by Django 5.2 on 2026-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_remove_dailymenu_special_note_dailymenu_dish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'canteen_combos',
            },
        ),
        migrations.CreateModel(
            name='CanteenDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dish_type', models.CharField(choices=[('solid', 'Solid Item (e.g. Idli, Dosa)'), ('liquid', 'Liquid Item (e.g. Sambar, Chutney)'), ('full_meal', 'Full Meal (e.g. Biriyani)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_veg', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'canteen_dishes',
            },
        ),
        migrations.CreateModel(
            name='CanteenIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'canteen_ingredients',
            },
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='combos',
            field=models.ManyToManyField(blank=True, related_name='menus', to='canteen.canteencombo'),
        ),
        migrations.AddField(
            model_name='canteencombo',
            name='dishes',
            field=models.ManyToManyField(related_name='combos', to='canteen.canteendish'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='menus', to='canteen.canteendish'),
        ),
        migrations.AddField(
            model_name='canteendish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='canteen.canteeningredient'),
        ),
    ]
