# Generated by Django 5.2 on 2026-04-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_canteencombo_canteendish_canteeningredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='menu_extras', to='canteen.canteeningredient'),
        ),
    ]
