# Generated by Django 5.2 on 2026-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_dailymenu_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteendish',
            name='dish_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
