# Generated by Django 5.2 on 2026-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_alter_canteendish_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenconsumptionlog',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canteendish',
            name='is_veg',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='canteenwastagelog',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
