# Generated by Django 5.2 on 2026-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_alter_canteenconsumptionlog_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteencombo',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='combos',
        ),
        migrations.AddField(
            model_name='canteencombo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canteencombo',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canteencombo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
