# Generated by Django 5.2 on 2026-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_remove_canteencombo_special_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch')], max_length=20)),
                ('title', models.CharField(help_text='Menu header, e.g. Special Breakfast', max_length=200)),
                ('items', models.JSONField(default=list, help_text='List of menu items/dishes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canteen_weekly_menus',
                'ordering': ['day', 'meal_type'],
                'unique_together': {('day', 'meal_type')},
            },
        ),
    ]
