# Generated by Django 5.2 on 2026-04-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_weeklymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'New Order'), ('stock', 'Low Stock'), ('system', 'System Alert')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canteen_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='canteenorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='items',
        ),
        migrations.AddField(
            model_name='canteenorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='food_items',
            field=models.ManyToManyField(blank=True, related_name='weekly_menus', to='canteen.fooditem'),
        ),
        migrations.AlterField(
            model_name='canteenorder',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='canteen.fooditem'),
        ),
        migrations.AlterField(
            model_name='canteenorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='canteenorder',
            table=None,
        ),
        migrations.CreateModel(
            name='CanteenPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_note', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='canteen.canteenorder')),
            ],
            options={
                'db_table': 'canteen_payments',
            },
        ),
    ]
