# Generated by Django 5.2 on 2026-04-17 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_canteennotification_alter_canteenorder_options_and_more'),
        ('students', '0006_alter_section_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteenorder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='canteenpayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='canteenorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='canteenorder',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_canteen_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canteenorder',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canteenpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='food_items',
            field=models.ManyToManyField(blank=True, related_name='daily_menus', to='canteen.fooditem'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='color',
            field=models.CharField(blank=True, default='#6366F1', max_length=20),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='icon',
            field=models.CharField(blank=True, default='🍽️', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Estimated prep time in minutes'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stock_count',
            field=models.PositiveIntegerField(default=100, help_text='Daily available quantity'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='times_ordered',
            field=models.PositiveIntegerField(default=0, help_text='Total times ordered'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='items',
            field=models.JSONField(default=list, help_text='List of menu items/dishes'),
        ),
        migrations.AlterField(
            model_name='canteenorder',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='canteen.fooditem'),
        ),
        migrations.AlterField(
            model_name='canteenorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='canteenorder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen_orders', to='students.student'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='canteen.canteenorder')),
            ],
            options={
                'db_table': 'canteen_order_items',
            },
        ),
    ]
