# Generated by Django 5.2 on 2026-04-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0014_backfill_fooditem_categories'),
        ('staff', '0003_teacherdetail_teaching_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen_orders', to='staff.staff'),
        ),
    ]
