# Generated by Django 5.2 on 2026-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0017_canteeninventorycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteeninventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
