# Generated by Django 5.2 on 2026-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0018_canteeninventoryitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteeninventoryitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
