# Generated by Django 5.2 on 2026-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0019_canteeninventoryitem_manufacturing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenpurchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
