# Generated by Django 5.2 on 2026-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0020_canteenpurchaseorder_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteensupplier',
            name='category',
        ),
        migrations.AddField(
            model_name='canteensupplier',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='canteen.canteeninventorycategory'),
        ),
    ]
