# Generated by Django 5.2 on 2026-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0021_remove_canteensupplier_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteensupplier',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
