# Generated by Django 6.0.3 on 2026-04-24 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0022_canteensupplier_alternate_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(blank=True, default='#3B82F6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canteen_shifts',
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='can_access_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='can_access_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='can_handle_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='leave_allowance_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='canteen/staff/photos/'),
        ),
        migrations.AddField(
            model_name='canteenstaffprofile',
            name='wage_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Wage')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='canteenstafftask',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Optional checklist items for the task'),
        ),
        migrations.CreateModel(
            name='CanteenStaffAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('menu_change', 'Menu Change'), ('inspection', 'Inspection'), ('holiday', 'Holiday'), ('shift_reminder', 'Shift Reminder'), ('emergency', 'Emergency Alert')], default='announcement', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_staff_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_staff_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenStaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('contract', 'Contract'), ('medical', 'Medical'), ('other', 'Other')], default='id_proof', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('file', models.FileField(upload_to='canteen/staff/documents/')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_staff_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenStaffLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave')], default='casual', max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteen_staff_leave_reviews', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_staff_leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenStaffPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hygiene_compliant', models.BooleanField(blank=True, null=True)),
                ('incident', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('note', 'Note'), ('reward', 'Reward'), ('warning', 'Warning')], default='note', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_staff_performance_logs', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_staff_performance_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenPayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use the first day of the month for grouping, e.g. 2026-04-01')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_canteen_payroll_records', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_payroll_records',
                'ordering': ['-month', 'staff_id'],
                'unique_together': {('staff', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CanteenStaffShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('swapped', 'Swapped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='canteen.canteenshift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='canteen.canteenstaffprofile')),
            ],
            options={
                'db_table': 'canteen_staff_shift_assignments',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date', 'shift')},
            },
        ),
    ]
