# Generated by Django 5.2 on 2026-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0023_canteenshift_canteenstaffprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenpurchaseorder',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='canteen/po_receipts/'),
        ),
    ]
