# Generated by Django 5.0.14 on 2026-04-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0016_finish_category_cleanup'),
        ('canteen', '0024_canteenpurchaseorder_receipt_file'),
    ]

    operations = [
    ]
