# Generated by Django 5.2 on 2026-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0025_merge_20260425_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenstaffannouncement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
