# Generated by Django 6.0.2 on 2026-04-01 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_rename_date_of_admission_student_admission_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_name", models.CharField(max_length=100)),
                ("stop_order", models.PositiveSmallIntegerField()),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("drop_time", models.TimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "ordering": ["stop_order"],
            },
        ),
        migrations.CreateModel(
            name="StudentTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="transport.routestop",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_transport",
            },
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("vehicle_capacity", models.PositiveSmallIntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transport_routes",
            },
        ),
        migrations.AddField(
            model_name="routestop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="transport.transportroute",
            ),
        ),
    ]
