# Generated by Django 5.2 on 2026-04-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportroute_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolbus',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
