# Generated by Django 5.2 on 2026-04-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_section_class_teacher'),
        ('transport', '0004_transportfeepayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportfee',
            unique_together={('student', 'period_label')},
        ),
    ]
