# Generated by Django 5.2 on 2026-04-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0005_alter_transportfee_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTransportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("boarding_time", models.TimeField(blank=True, null=True)),
                ("exiting_time", models.TimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual Entry"), ("mobile", "Mobile App"), ("rfid", "RFID/Scanner")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_logs",
                        to="transport.schoolbus",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_student_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_logs",
                        to="transport.transportroute",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_logs",
                        to="transport.routestop",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_logs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_transport_logs",
                "ordering": ["-date", "student_id"],
                "unique_together": {("student", "date")},
                "indexes": [
                    models.Index(fields=["date", "route"], name="stud_trlog_date_route_idx"),
                    models.Index(fields=["student", "date"], name="stud_trlog_student_date_idx"),
                ],
            },
        ),
    ]

