# Generated by Django 6.0.3 on 2026-04-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_academicyear_timetable_config'),
        ('fees', '0001_initial'),
        ('students', '0006_alter_section_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='fee_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('miscellaneous', 'Miscellaneous')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='concession_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('upi', 'UPI'), ('neft', 'NEFT/RTGS')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annually', 'Annually'), ('per_term', 'Per Term')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concession_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('full_waiver', 'Full Waiver')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('applicable_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions', to='fees.feecategory')),
            ],
            options={
                'db_table': 'fee_concessions',
            },
        ),
        migrations.CreateModel(
            name='FeeInstalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='fees.feestructure')),
            ],
            options={
                'db_table': 'fee_instalments',
                'ordering': ['instalment_number'],
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='instalment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.feeinstalment'),
        ),
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_concessions', to='accounts.academicyear')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_concessions', to=settings.AUTH_USER_MODEL)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_concessions', to='fees.concession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='students.student')),
            ],
            options={
                'db_table': 'student_concessions',
            },
        ),
    ]
